apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
<<<<<<< HEAD
        image: localhost:5000/app1:8812a8f
=======
        image: k3d-istio-registry:5000/app1:latest  # This will be replaced by CI with correct tag
>>>>>>> f707e2f (update code)
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
  - port: 80
    targetPort: 80
