name: Build and Push App1 to K3D

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'apps/app1.yaml'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    if: github.actor != 'github-actions[bot]'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Get full history
        persist-credentials: true  # Maintain auth for push

    - name: Get short commit SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Configure Docker for k3d registry
      run: docker login k3d-istio-registry:5000 -u dummy -p dummy

    - name: Build and push Docker image
      run: |
        docker build -t k3d-istio-registry:5000/app1:${{ steps.vars.outputs.sha_short }} .
        docker push k3d-istio-registry:5000/app1:${{ steps.vars.outputs.sha_short }}

    - name: Update and commit manifest
      run: |
        # First reset any changes (in case of previous failed runs)
        git reset --hard HEAD
        
        # Pull latest changes
        git pull origin main
        
        # Make and commit changes
        sed -i "s|image: .*|image: k3d-istio-registry:5000/app1:${{ steps.vars.outputs.sha_short }}|" apps/app1.yaml
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add apps/app1.yaml
        git commit -m "CI: Update app1 to ${{ steps.vars.outputs.sha_short}} [skip ci]"
        
        # Push changes
        git push origin main
